### ISSUE TITLE
Online demo

### ISSUE THREAD

**Issue by Atinux** [jurassicjs/nuxt3-fullstack-tutorial#4]
Any plan to deploy it to have a live demo of it? :)

**Comment by rohrig** [comment]
Hi @Atinux,  yes. I'm busier than a one legged man in a butt kicking contest right now. 😄 I plan to make a webhooks tutorial then make it a bit prettier and then go live. I'll keep you posted. Any recommendations on where to deploy?

**Comment by Atinux** [comment]
I would go with Vercel or Netlify 😊

**Comment by rohrig** [comment]
@Atinux The Demo is live!

It's still a work in progess. 

I’ll be making a deployment video soon. I went with github actions to begin with, but I plan to make many videos about many different deployment strategies in the future. 

**Please thank the entire Nuxt team from me. You guys do awesome work and it makes making these tutorials a lot of fun.** 

https://fullstackjack.dev

**Comment by Atinux** [comment]
Beautiful 😍
